BEGIN;

DROP TABLE IF EXISTS users;
CREATE TABLE users (
  id SERIAL PRIMARY KEY,
  stripe_id VARCHAR(100) UNIQUE,
  email VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(200) NOT NULL,
  register_date DATE DEFAULT CURRENT_DATE
);

COMMIT ;